# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ya-P19mwkuhWPlp2fJdrw6cYATiheNs8
"""

grafo = {
    "A": ["B", "C"],
    "B": ["D", "E"],
    "C": ["F"],
    "D": [],
    "E": ["G"],
    "F": [],
    "G": []
}

def dfs_visual(nodo, visitados, resultado, profundidad, stats):

    visitados.add(nodo)
    resultado.append(nodo)

    stats['max_profundidad'] = max(stats['max_profundidad'], profundidad)

    indent = "   " * (profundidad - 1)

    print(f"{indent}-> Entrando a: {nodo}")

    for vecino in grafo[nodo]:
        if vecino not in visitados:
            dfs_visual(vecino, visitados, resultado, profundidad + 1, stats)

    print(f"{indent}<- Saliendo de: {nodo}")

    return resultado, stats['max_profundidad']


print("ESTRUCTURA DEL ÁRBOL:")
print("      A")
print("     / \\")
print("    B   C")
print("   / \\   \\")
print("  D   E   F")
print("     /")
print("    G\n")


stats = {"max_profundidad": 0}

res_dfs, mem_dfs = dfs_visual("A", set(), [], 1, stats)

print("\nRESULTADO DFS:", res_dfs)
print("PROFUNDIDAD MÁXIMA (MEMORIA DFS):", mem_dfs)