# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ya-P19mwkuhWPlp2fJdrw6cYATiheNs8
"""

from collections import deque

grafo = {
    "A": ["B", "C"],
    "B": ["D", "E"],
    "C": ["F"],
    "D": [],
    "E": ["G"],
    "F": [],
    "G": []
}

def bfs_profesional(inicio):
    visitados = {inicio}
    resultado = []
    cola = deque([inicio])
    max_memoria = 1

    print("--- PASOS BFS (POR NIVELES) ---")
    while cola:
        max_memoria = max(max_memoria, len(cola))
        nodo = cola.popleft()
        resultado.append(nodo)

        for vecino in grafo[nodo]:
            if vecino not in visitados:
                visitados.add(vecino)
                cola.append(vecino)

        # La sugerencia que te dieron para ver el proceso real:
        print(f"Visitando: {nodo} | Cola en espera: {list(cola)}")

    return resultado, max_memoria

# Dibujo del árbol para referencia
print("ESTRUCTURA DEL ÁRBOL:")
print("      A")
print("     / \\")
print("    B   C")
print("   / \\   \\")
print("  D   E   F")
print("     /")
print("    G\n")

res_bfs, mem_bfs = bfs_profesional("A")
print("\nRESULTADO FINAL BFS (Camino):", res_bfs)
print("MEMORIA MÁXIMA BFS (Nodos en cola):", mem_bfs)
